using Gmsh
import Gmsh: gmsh
gmsh.initialize()
gmsh.option.setNumber("General.Terminal", 1)
gmsh.option.setNumber("Mesh.Algorithm", 6)
gmsh.merge("Models/Simple/ComsolBin.stl")
onedtuples::Vector{Tuple{Int32, Int32}} = gmsh.model.getEntities(1)
onedtags = map(x -> x[2] , onedtuples)
gmsh.model.addPhysicalGroup(1, onedtags,  1, "Model1d")
twodtuples::Vector{Tuple{Int32, Int32}} = gmsh.model.getEntities(2)
twodtags::Vector{Int32} = map(x -> x[2] , twodtuples)
gmsh.model.addPhysicalGroup(2, twodtags,  2, "Model2d")
threedtuples::Vector{Tuple{Int32, Int32}} = gmsh.model.getEntities(3)
threedtags = map(x -> x[2] , threedtuples)
gmsh.model.addPhysicalGroup(3, threedtags,  3, "Model3d")
gmsh.model.geo.synchronize()
gmsh.model.mesh.generate(3)
gmsh.write("Models/Simple/ComsolBin.msh")
gmsh.finalize()